preconnect:
  - https://gcore.jsdelivr.net
  - https://unpkg.com
  - https://cdn.bootcdn.net

inject:
  head:
    - <link rel="shortcut icon" href="/assets/xaoxuu/favicon/favicon.ico">
    - <meta name="theme-color" content="#f8f8f8">
    - <link rel="stylesheet" href="https://cdn.bootcdn.net/ajax/libs/lxgw-wenkai-screen-webfont/1.7.0/style.min.css" media="all" />
    - <link href="https://cdn.bootcdn.net/ajax/libs/font-awesome/6.4.2/css/brands.min.css" rel="stylesheet" media="all">
    - <link href="https://cdn.bootcdn.net/ajax/libs/font-awesome/6.4.2/css/all.css" rel="stylesheet">

# menubar:
#    items: 
#      - id: post
#        theme: '#1BCDFC'
#        icon: solar:documents-bold-duotone
#        title: 博客
#        url: /
#      - id: projects
#        theme: '#3DC550'
#        icon: solar:notebook-bookmark-bold-duotone
#        title: 归档
#        url: /projects/
#      - id: workouts
#        theme: '#FA6400'
#        icon: solar:planet-bold-duotone
#        title: 运动
#        url: /workouts/
#      - id: about
#        theme: '#F44336'
#        icon: solar:chat-square-like-bold-duotone
#        title: 关于
#        url: /about/

site_tree:
  home:
    sidebar: starter, welcome, recent
  index_blog:
    sidebar: starter, welcome, recent
  index_archive:
    menu_id: archives
  topic:
    menu_id: topic

article:
  auto_cover: false
  share: [wechat, weibo, email, link]


style:
  text-align: justify
  smooth_scroll: false
  codeblock:
    scrollbar: 0px
  font-size:
    body: 1rem
  font-family:
    logo: '"LXGW WenKai Screen", system-ui, "Microsoft Yahei", "Segoe UI", -apple-system, Roboto, Ubuntu, "Helvetica Neue", Arial, "WenQuanYi Micro Hei", sans-serif'
    body: '"LXGW WenKai Screen", system-ui, "Microsoft Yahei", "Segoe UI", -apple-system, Roboto, Ubuntu, "Helvetica Neue", Arial, "WenQuanYi Micro Hei", sans-serif'
    code: '"LXGW WenKai Screen", Menlo, Monaco, Consolas, system-ui, "Courier New", monospace, sans-serif'
    codeblock: 'Menlo, Monaco, Consolas, system-ui, "Courier New", monospace, sans-serif'

comments:
  service: utterances
  utterances:
    repo: zhaohongxuan/zhaohongxuan.github.io
